// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akzayvoltyikdixdcuok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFremF5dm9sdHlpa2RpeGRjdW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODA3NDIsImV4cCI6MjA2MDU1Njc0Mn0._PNjRql6RUd8viDJWlo72ScSPMUT5Uc5vS86ZJdVPqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY) as unknown as SupabaseClient<any>;
