// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvrsqtnoihpycmxsqcgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2cnNxdG5vaWhweWNteHNxY2d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4MDM4MzksImV4cCI6MjA4NjM3OTgzOX0.tj21qyCsIGmi2GvwTaNiYOpakWo-RKaXoRiwmbMsqug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY) as unknown as SupabaseClient<any>;
